# -*- coding: utf-8 -*-
"""Tiny SQLite Database using Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yh3zjkVcFm2vP04N5ixuFeF3j5RyyDPi
"""

# SALES ANALYSIS USING PYTHON + SQLITE

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import os

# STEP 1 — CONNECT / CREATE DATABASE
db_file = "sales_data.db"

if os.path.exists(db_file):
    os.remove(db_file)

conn = sqlite3.connect(db_file)
cursor = conn.cursor()

# STEP 2 — CREATE SALES TABLE
cursor.execute("""
CREATE TABLE sales (
   id INTEGER PRIMARY KEY,
  sale_date TEXT,
  product TEXT,
  quantity INTEGER,
  price REAL
)
""")

# STEP 3 — INSERT SAMPLE DATA
sample_rows=[
    ("Notebook",   "2025-01-01", 10, 2.50),
    ("Notebook",   "2025-01-02",  5, 2.50),
    ("Pen",        "2025-01-01", 40, 0.99),
    ("Pen",        "2025-01-03", 30, 0.99),
    ("Stapler",    "2025-01-02",  3, 5.00),
    ("Stapler",    "2025-01-04",  2, 5.00),
    ("Highlighter","2025-01-03", 12, 1.20),
    ("Highlighter","2025-01-05",  8, 1.20)
]

cursor.executemany("""
INSERT INTO sales (product, sale_date, quantity, price)
VALUES (?, ?, ?, ?)
""", sample_rows)

conn.commit()

# STEP 4 — QUERY 1: SALES SUMMARY BY PRODUCT
query_product = """
SELECT product,
    SUM(quantity) AS total_quantity,
    SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
ORDER BY revenue DESC
"""

df_products = pd.read_sql_query(query_product, conn)

print("Sales by Product:")
print(df_products)
print("\n")

# STEP 5 — QUERY 2: OVERALL TOTALS
query_totals="""
SELECT
    SUM(quantity) AS total_quantity,
    SUM(quantity * price) AS total_revenue
FROM sales
"""

df_totals = pd.read_sql_query(query_totals, conn)

print("Overall Totals:")
print(df_totals)
print("\n")

# STEP 6 — BAR CHART (REVENUE BY PRODUCT)
plt.figure(figsize=(7,5))
plt.bar(df_products["product"], df_products["revenue"])
plt.xlabel("Product")
plt.ylabel("Revenue")
plt.title("Revenue by Product")
plt.tight_layout()
plt.show()

# Save chart
plt.savefig("sales_chart.png")

# Close DB connection
conn.close()